apiVersion: v1
kind: ConfigMap
metadata:
  name: masters-pool-api-config
  labels:
    app.kubernetes.io/name: masters-pool
    app.kubernetes.io/component: api
data:
  HTTP_ADDR: ":8080"
  GOLF_PROVIDER: ""
  GOLF_API_BASE_URL: "https://live-golf-data.p.rapidapi.com"
  GOLF_API_HOST: "live-golf-data.p.rapidapi.com"
