apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: masters-pool
  labels:
    app.kubernetes.io/name: masters-pool
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - masters-pool.example.com
      secretName: masters-pool-tls
  rules:
    - host: masters-pool.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: masters-pool
                port:
                  number: 80
