apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: masters-pool
resources:
  - namespace.yaml
  - api-configmap.yaml
  - web-configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
